import React, { useState } from 'react';
import { Layers, Download, Loader2 } from 'lucide-react';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import FileDropzone from '../components/FileDropzone';

type HFPosition = 'left' | 'center' | 'right';

export default function HeadersFooters() {
  const [file, setFile] = useState<File | null>(null);
  const [headerText, setHeaderText] = useState('Confidential Document');
  const [footerText, setFooterText] = useState('Generated by PDF Tools');
  const [headerPos, setHeaderPos] = useState<HFPosition>('left');
  const [footerPos, setFooterPos] = useState<HFPosition>('left');
  const [fontSize, setFontSize] = useState(10);
  const [addPageNumbers, setAddPageNumbers] = useState(true);
  const [addDate, setAddDate] = useState(false);
  const [resultUrl, setResultUrl] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const handleDrop = (files: File[]) => {
    if (files[0]) { setFile(files[0]); setResultUrl(null); }
  };

  const handleProcess = async () => {
    if (!file) return;
    setBusy(true);
    try {
      const arrayBuffer = await file.arrayBuffer();
      const pdfDoc = await PDFDocument.load(arrayBuffer);
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const pages = pdfDoc.getPages();
      const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
      
      pages.forEach((page, idx) => {
        const { width, height } = page.getSize();

        // Header
        if (headerText.trim()) {
          let hText = headerText;
          if (addDate) hText = `${hText}  |  ${dateStr}`;
          const tw = font.widthOfTextAtSize(hText, fontSize);
          let hx = 30;
          if (headerPos === 'center') hx = (width - tw) / 2;
          if (headerPos === 'right') hx = width - tw - 30;
          page.drawText(hText, {
            x: hx, y: height - 25,
            size: fontSize, font,
            color: rgb(0.4, 0.4, 0.4),
          });
        }

        // Footer
        let fText = footerText.trim() || '';
        if (addPageNumbers) {
          const pn = `Page ${idx + 1} of ${pages.length}`;
          fText = fText ? `${fText}  |  ${pn}` : pn;
        }
        if (fText) {
          const tw = font.widthOfTextAtSize(fText, fontSize);
          let fx = 30;
          if (footerPos === 'center') fx = (width - tw) / 2;
          if (footerPos === 'right') fx = width - tw - 30;
          page.drawText(fText, {
            x: fx, y: 15,
            size: fontSize, font,
            color: rgb(0.4, 0.4, 0.4),
          });
        }
      });

      const pdfBytes = await pdfDoc.save();
      const blob = new Blob([pdfBytes], { type: 'application/pdf' });
      setResultUrl(URL.createObjectURL(blob));
    } catch (e: any) {
      alert(e?.message || 'Headers/Footers failed.');
    } finally {
      setBusy(false);
    }
  };

  const posBtn = (val: HFPosition, current: HFPosition, setter: (v: HFPosition) => void) => (
    <button onClick={() => setter(val)} className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${current === val ? 'bg-teal-50 border-teal-500 text-teal-700' : 'border-gray-200 text-gray-600 hover:bg-gray-50'}`}>
      {val.charAt(0).toUpperCase() + val.slice(1)}
    </button>
  );

  return (
    <div className="flex-1 flex flex-col items-center justify-center p-8">
      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Add Headers & Footers</h1>
        <p className="text-xl text-gray-600">Add custom headers and footers to every page of your PDF.</p>
      </div>
      {!file ? (
        <FileDropzone onDrop={handleDrop} multiple={false} title="Select PDF file" />
      ) : (
        <div className="w-full max-w-2xl bg-white rounded-2xl shadow-sm border border-gray-200 p-8 space-y-5">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Header Text</label>
            <input type="text" value={headerText} onChange={e => setHeaderText(e.target.value)} className="w-full px-3 py-2 border border-gray-300 rounded-lg" placeholder="Leave blank for no header" />
            <div className="flex gap-2 mt-2">{posBtn('left', headerPos, setHeaderPos)}{posBtn('center', headerPos, setHeaderPos)}{posBtn('right', headerPos, setHeaderPos)}</div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Footer Text</label>
            <input type="text" value={footerText} onChange={e => setFooterText(e.target.value)} className="w-full px-3 py-2 border border-gray-300 rounded-lg" placeholder="Leave blank for no footer" />
            <div className="flex gap-2 mt-2">{posBtn('left', footerPos, setFooterPos)}{posBtn('center', footerPos, setFooterPos)}{posBtn('right', footerPos, setFooterPos)}</div>
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Font Size</label>
              <input type="number" value={fontSize} min={6} max={20} onChange={e => setFontSize(Number(e.target.value))} className="w-full px-3 py-2 border border-gray-300 rounded-lg" />
            </div>
            <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
              <input type="checkbox" checked={addPageNumbers} onChange={e => setAddPageNumbers(e.target.checked)} className="rounded" />
              Page numbers
            </label>
            <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
              <input type="checkbox" checked={addDate} onChange={e => setAddDate(e.target.checked)} className="rounded" />
              Date stamp
            </label>
          </div>
          <div className="flex gap-3 pt-2">
            <button onClick={handleProcess} disabled={busy} className="flex-1 py-3 bg-teal-600 text-white font-bold rounded-xl hover:bg-teal-700 disabled:opacity-50 flex items-center justify-center gap-2">
              {busy ? <Loader2 className="w-5 h-5 animate-spin" /> : <Layers className="w-5 h-5" />}
              {busy ? 'Adding…' : 'Add Headers/Footers'}
            </button>
            <button onClick={() => { setFile(null); setResultUrl(null); }} className="px-5 py-3 bg-gray-100 text-gray-700 font-semibold rounded-xl hover:bg-gray-200">Cancel</button>
          </div>
          {resultUrl && (
            <div className="p-6 bg-green-50 rounded-xl border border-green-200 text-center">
              <a href={resultUrl} download={`headers_${file.name}`} className="inline-flex items-center gap-2 px-6 py-3 bg-green-600 text-white font-bold rounded-xl hover:bg-green-700">
                <Download className="w-5 h-5" /> Download
              </a>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
