import React from 'react';
import { Layers } from 'lucide-react';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import GenericToolUI from '../components/GenericToolUI';

export default function HeadersFooters() {
  const handleProcess = async (file: File): Promise<string> => {
    const arrayBuffer = await file.arrayBuffer();
    const pdfDoc = await PDFDocument.load(arrayBuffer);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    
    const pages = pdfDoc.getPages();
    
    pages.forEach((page) => {
      const { width, height } = page.getSize();
      
      // Header
      page.drawText('Confidential Document', {
        x: 30,
        y: height - 30,
        size: 10,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });

      // Footer
      page.drawText('Generated by PDF Tools', {
        x: 30,
        y: 20,
        size: 10,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });
    });

    const pdfBytes = await pdfDoc.save();
    const blob = new Blob([pdfBytes], { type: 'application/pdf' });
    return URL.createObjectURL(blob);
  };

  return (
    <GenericToolUI 
      title="Add Headers & Footers"
      description="Automatically apply a default header and footer to every page."
      icon={Layers}
      colorClass="text-teal-600"
      bgClass="bg-teal-50"
      actionText="Add Headers/Footers"
      onProcess={handleProcess}
    />
  );
}
